In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

doc1 = "He is a lazy boy. She is also lazy."
doc2 = "Neeraj is a lazy person."

bow_vectorizer = CountVectorizer()

X = bow_vectorizer.fit_transform([doc1,doc2])

bow_df = pd.DataFrame(X.toarray(),columns=bow_vectorizer.get_feature_names_out())
bow_df.head()

also  boy  he  is  lazy  neeraj  person  she
0     1    1   1   2     2       0       0    1
1     0    0   0   1     1       1       1    0

In [12]:
import numpy as np
np.random.seed(42)
v_revenge = np.array([0,0,1,0,0,0]) #"revenge"
print(v_revenge)

weight = np.random.random_sample((6,3))
print(weight)

hidden_layer_sg = np.dot(v_revenge,weight)
print(hidden_layer_sg)

weight_prime = np.random.random_sample((3,6))
print(weight_prime)

o_the = np.dot(hidden_layer_sg, weight_prime)
print(o_the)

[0 0 1 0 0 0]
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]]
[0.05808361 0.86617615 0.60111501]
[[0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735]]
[0.7853302  0.79952094 0.24759478 1.02390925 1.1105601  0.54745364]


In [13]:
v_the = np.array([0,0,1,0,0,0]) #"the"
print(v_the)

hidden_layer_cbow = np.dot(v_the,weight)
print(hidden_layer_cbow)

o_revenge = np.dot(hidden_layer_cbow, weight_prime)
print(o_revenge)

[0 0 1 0 0 0]
[0.05808361 0.86617615 0.60111501]
[0.7853302  0.79952094 0.24759478 1.02390925 1.1105601  0.54745364]


In [3]:
import re
import numpy as np

from gensim.models import Word2Vec
from nltk.corpus import gutenberg
from multiprocessing import Pool
from scipy import spatial

import gensim
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import string


In [4]:
import nltk

from nltk.corpus import gutenberg

In [2]:
import pandas as pd
# DATASET DARI FILE PERTEMUAN KE 3 (BOOLEAN MODEL)
# Baca teks dari file 'lee quan yew.txt'
with open('/content/data.txt', 'r', encoding='utf-8') as file:
    text = file.read()

# Buat DataFrame dari teks
df = pd.DataFrame({'Text': [text]})

# Tampilkan DataFrame
print(df)


                                                Text
0  Jakarta, CNN Indonesia -- Pep Guardiola akhirn...


In [5]:
# Membangun model Word2Vec
model = Word2Vec(df['Text'], vector_size=100, window=5, min_count=1, sg=0)

# Melatih model
model.train(df['Text'], total_examples=len(df['Text']), epochs=10)


(5594, 26630)

In [6]:
# Mencari kata-kata yang ada dalam kosakata model
vocab = model.wv.index_to_key
print(vocab)


[' ', 'a', 'e', 'i', 'n', 't', 'r', 's', 'u', 'd', 'm', 'l', 'p', 'g', 'k', 'h', 'o', 'b', 'y', 'c', '.', ',', 'w', 'f', 'S', 'j', 'G', 'M', 'P', '-', 'K', 'v', '“', '1', '”', 'I', 'C', 'B', 'J', 'A', 'F', '(', '2', ')', 'T', 'L', 'H', "'", 'N', 'Y', 'D', '3', '9', '[', ']', 'W', '/', 'O', '0', '5', '7']


In [7]:
similar_words = model.wv.most_similar('s', topn=10)
print(similar_words)


[('B', 0.9992157220840454), ('1', 0.9992015957832336), ('o', 0.9991753101348877), ('r', 0.999172031879425), ('c', 0.9991673231124878), ('.', 0.9991466999053955), (' ', 0.999122679233551), ('e', 0.9991074204444885), ('I', 0.9990980625152588), ('l', 0.9990413784980774)]


In [8]:
from gensim.models import Word2Vec

# Membangun model Skip-gram
skipgram_model = Word2Vec(df['Text'], vector_size=100, window=5, min_count=1, sg=1)

# Melatih model Skip-gram
skipgram_model.train(df['Text'], total_examples=len(df['Text']), epochs=10)

(5594, 26630)

In [9]:
# Mencari kata-kata serupa dengan kata tertentu dari model skipgram
similar_words = skipgram_model.wv.most_similar('s', topn=10)
print("Kata-kata serupa dengan 's' (dari model Skip-gram):")
for word, score in similar_words:
    print(f"{word}: {score}")

# Menampilkan vektor kata untuk kata tertentu
vector = skipgram_model.wv['s']
print("Vektor kata untuk 's' (dari model Skip-gram):")
print(vector)

Kata-kata serupa dengan 's' (dari model Skip-gram):
c: 0.9970273375511169
v: 0.9969329833984375
W: 0.9965360760688782
l: 0.9964099526405334
i: 0.9962394833564758
f: 0.9962062835693359
Y: 0.9962048530578613
]: 0.9961782693862915
O: 0.9961727857589722
': 0.996157705783844
Vektor kata untuk 's' (dari model Skip-gram):
[-0.00874494  0.12464108  0.03574384  0.14272512  0.08611456 -0.09261786
  0.16854893  0.18440428 -0.11285492 -0.11765001  0.08798005 -0.14399342
  0.00304949  0.14000782 -0.02119653  0.0078637   0.2231428   0.04148151
 -0.12348541 -0.24825583  0.11272263 -0.04387752  0.22559768 -0.10781479
 -0.03130107  0.03287421 -0.18757881  0.13537943 -0.04000556  0.01165437
  0.14182568 -0.03698987  0.10675681 -0.20878492 -0.02886928  0.00826764
  0.10621784  0.07483903 -0.05122445 -0.00385018  0.00367029 -0.04452657
 -0.03720948  0.02539654  0.07674455 -0.02296766 -0.04204811 -0.05377861
  0.09011387  0.0895918   0.05728262 -0.06498325 -0.06077159 -0.12871476
 -0.01655697 -0.06576777  

In [10]:
from gensim.models import Word2Vec

# Membangun model CBOW
cbow_model = Word2Vec(df['Text'], vector_size=100, window=5, min_count=1, sg=0)

# Melatih model CBOW
cbow_model.train(df['Text'], total_examples=len(df['Text']), epochs=10)

(5594, 26630)

In [11]:
# Mencari kata-kata serupa dengan kata tertentu dari model CBOW
similar_words = cbow_model.wv.most_similar('l', topn=10)
print("Kata-kata serupa dengan 'l' (dari model CBOW):")
for word, score in similar_words:
    print(f"{word}: {score}")

# Menampilkan vektor kata untuk kata tertentu dari model CBOW
vector = cbow_model.wv['l']
print("Vektor kata untuk 'l' (dari model CBOW):")
print(vector)

Kata-kata serupa dengan 'l' (dari model CBOW):
.: 0.999252200126648
e: 0.9992106556892395
1: 0.9991708993911743
,: 0.9991546273231506
2: 0.9990965723991394
B: 0.9990777373313904
r: 0.9990472197532654
s: 0.9990412592887878
M: 0.9990251064300537
K: 0.999021589756012
Vektor kata untuk 'l' (dari model CBOW):
[-4.07433137e-02  1.75450951e-01  5.72798364e-02  1.65822744e-01
  7.20779151e-02 -2.08211392e-01  2.50145704e-01  3.88814092e-01
 -1.98451728e-01 -2.77288586e-01  1.70949802e-01 -2.25610003e-01
 -3.07260938e-02  1.64102390e-01  1.12849334e-02 -3.89799452e-03
  3.30636650e-01  6.05613962e-02 -1.61332265e-01 -4.64793563e-01
  1.12569697e-01 -3.03764082e-02  3.66806448e-01 -1.31036982e-01
 -2.62527522e-02  5.69016859e-02 -2.62700111e-01  1.61943853e-01
 -8.95879418e-02  2.62997188e-02  2.18944818e-01 -1.00923873e-01
  1.86496779e-01 -3.05560201e-01 -7.94532970e-02  7.85703138e-02
  1.48762316e-01  4.03451435e-02 -1.05619229e-01 -5.96827641e-02
  3.01863272e-02 -9.72791165e-02 -1.05927035